# Generated by Django 3.2.2 on 2021-05-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemodel',
            old_name='licence_place',
            new_name='license_place',
        ),
    ]
